# Generated by Django 4.2.5 on 2023-09-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_file', models.FileField(blank=True, upload_to='record/videos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
