# Generated by Django 4.2.5 on 2023-09-28 18:59

import django.core.validators
from django.db import migrations, models
import record.validators


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_recordedvideo_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedvideo',
            name='video_file',
            field=models.FileField(blank=True, upload_to='record/videos/', validators=[record.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi'])]),
        ),
    ]
