# Generated by Django 4.2.5 on 2023-09-30 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import record.validators


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_recordedvideo_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedvideo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recordedvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='record/videos/', validators=[record.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi'])]),
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_text', models.TextField(null=True)),
                ('recorded_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='record.recordedvideo')),
            ],
        ),
    ]
