# Generated by Django 3.2.21 on 2023-10-02 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_recordedvideo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedvideo',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recordedvideo',
            name='video_file',
            field=models.FileField(blank=True, default=0, upload_to='record/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi'])]),
            preserve_default=False,
        ),
    ]
